# Site settings
email: sage@latorra.org
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: sage
description: 
url: ""
twitter_username: olde_fortran
default_img: 

# Profile settings
name: Sage LaTorra
profile_img: 
profile: Game designer and Senior Test Engineer at Google
social:
  github: https://github.com/Sagelt
  twitter: https://twitter.com/olde_fortran

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
