# Site settings
email: sage@latorra.org
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: LaTorra.org
description: 
url: ""
twitter_username: olde_fortran
default_img: 

# Profile settings
name: Sage LaTorra
profile_img: /images/sage.jpg
profile: Sage LaTorra is a game designer and senior test engineer at Google. You may know him from Dungeon World.
social:
  feed: /blog/
  google-plus: https://plus.google.com/+SageLaTorra
  twitter: https://twitter.com/olde_fortran
  github: https://github.com/Sagelt

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
